Add css-layout-simple
manuelbarzi/skylab-bootcamp-201804 pull request #63
Opened 2018-04-12 10:38 UTC by lgimeneza

2018-04-12 15:14 UTC, MinaZhen approved these changes

2018-04-12 15:14 UTC, MinaZhen commented on staff/lgimeneza/css-layout-simple-adaptive/styles/main.css
> +}
I have to complain...you know why ;P you could save extra space writting together header & footer... and in mobile.css, nav & aside

2018-04-12 15:15 UTC, MuyZan commented
Well done!

2018-04-13 07:42 UTC, agandia9 commented on staff/lgimeneza/css-layout-simple/styles/main.css
> +}
Should you use the selector by class when there is not more than one element using that class? investigate the selector by tag

2018-04-13 08:15 UTC, manuelbarzi commented on staff/lgimeneza/css-layout-simple/styles/main.css
> +.mainContent{
TIP may you use chain-case selector names, instead of camelCase ones

2018-04-14 22:57 UTC, MuyZan requested changes
:D

2018-04-14 22:57 UTC, MuyZan commented on staff/lgimeneza/portfolio/styles/main.css
> +}
Maybe you can group some common rules (check section-header and site-footer)

![](https://media.giphy.com/media/xk0vJLeQvzaes/giphy.gif)

2018-04-17 07:18 UTC, agandia9 commented on staff/lgimeneza/css-layout-simple-adaptive/index.html
> +    <!-- <link rel="stylesheet" href="styles/mobile.css"> -->
Delete comments before push!

2018-04-17 07:56 UTC, lgimeneza commented on staff/lgimeneza/css-layout-simple-adaptive/index.html
> +    <!-- <link rel="stylesheet" href="styles/mobile.css"> -->
Done!

2018-04-17 07:56 UTC, agandia9 reviewed
yea!

2018-04-17 07:56 UTC, merged